// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztylvutwwgpqhoetewvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0eWx2dXR3d2dwcWhvZXRld3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzEyOTEsImV4cCI6MjA1NzEwNzI5MX0.FT-cgLYom6K2bbHurZCGcdVtUn8RqMV4WNwjM8sNyXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);